### PR TITLE
fix: check sdkVersion when uploading new APK

### LINKED ISSUE #2042: Check `minSdkVersion` >= 26 when uploading new APKs
Check `minSdkVersion` when a new APK version (`ApplicationVersion`) are uploaded at http://localhost:8080/webapp/admin/application/create

<kbd>Image</kbd>

If below minimum version requirement, return an error.

---

* Relates to #2047

### PR DESCRIPTION
**Pull request by ideal3147**
### Issue Number

* Resolves #2042 

### Purpose

* Check minSdkVersion when a new APK version (ApplicationVersion) are uploaded at
 http://localhost:8080/webapp/admin/application-version/create?applicationId=xxx

### Technical Details

* Check minSdkVersion when a new APK version (ApplicationVersion) are uploaded
* If below minimum version requirement, return an error.

### CODE REVIEW

File: src/main/java/ai/elimu/web/admin/application_version/ApplicationVersionCreateController.java [hunk 1]
```diff
@@ -125,6 +127,9 @@ public String handleSubmit(
           applicationVersion.setLabel(label);
 
           Integer minSdkVersion = Integer.valueOf(apkMeta.getMinSdkVersion());
+          if (minSdkVersion < MIN_SDK_VERSION) {
+            result.reject("TooLow.sdkVersionCode");
```
Comment (jo-elimu) [inline src/main/java/ai/elimu/web/admin/application_version/ApplicationVersionCreateController.java:131]: I suggest removing the "Code" part of this name, just to avoid confusion with the `versionCode`.

```suggestion
            result.reject("TooLow.sdkVersion");
```

**Review by jo-elimu — APPROVED** [review]

**Review by jo-elimu — APPROVED** [review]
