### PR TITLE
fix: Incomplete import of ePUB from Let's Read #1527

### LINKED ISSUE #1527: Incomplete import of ePUB from Let's Read
**Describe the bug**
I downloaded an ePUB from https://www.letsreadasia.org/book/377b7e63-6126-4cfe-bcee-1538d75c1b2f?bookLang=4846240843956224 and tried to import it to the website, but none of the chapters where imported: http://eng.elimu.ai/content/storybook/edit/72

**To Reproduce**
1. Go to https://www.letsreadasia.org/book/377b7e63-6126-4cfe-bcee-1538d75c1b2f?bookLang=4846240843956224
2. Click on 'Download Epub'
3. Go to http://eng.elimu.ai/content/storybook/create-from-epub and upload the file

**Expected behavior**
All storybook chapters should be imported.

**Screenshots**
Screen Shot 2022-03-24 at 2 27 06 PM

### PR DESCRIPTION
**Pull request by nya-elimuai**
Fixes #1527

Screen Shot 2022-03-25 at 1 41 48 PM

### CODE REVIEW

File: src/main/java/ai/elimu/util/epub/EPubParagraphExtractionHelper.java [hunk 1]
```diff
@@ -119,6 +119,61 @@
...
+                            <div lang="en">
+                                <div class="container">
+                                    <img src="p-1.jpg" alt=""/>
+                                </div>
+                                <p dir="auto">The moon rises.</p>
+                            </div>
+                        */
+                        if ("div".equals(bodyChildNode.getNodeName()) && (bodyChildNode.getAttributes().getNamedItem("lang") != null)) {
+                            NodeList langDivChildNodeList = bodyChildNode.getChildNodes();
+                            logger.info("langDivChildNodeList: " + langDivChildNodeList);
```
Comment (jo-elimu) [inline src/main/java/ai/elimu/util/epub/EPubParagraphExtractionHelper.java:134]: To avoid mixing with variable names already used above, consider renaming from "child node" to "paragraph container" or something similar?

**Review by jo-elimu — CHANGES_REQUESTED** [review]
I suggest refactoring to avoid code duplication.

**Review by jo-elimu — APPROVED** [review]
