### PR TITLE
1191 Fix UnsupportedOperationException during startup

### LINKED ISSUE #1191: Fix UnsupportedOperationException during startup
```
20:17:47.509 [main] WARN  org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator - HHH000181: No appropriate connection provider encountered, assuming application will be supplying connections
20:17:47.509 [main] WARN  org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator - HHH000342: Could not obtain connection to query metadata
java.lang.UnsupportedOperationException: The application must supply JDBC connections
	at org.hibernate.engine.jdbc.connections.internal.UserSuppliedConnectionProviderImpl.getConnection(UserSuppliedConnectionProviderImpl.java:44) ~[hibernate-core-5.4.26.Final.jar:5.4.26.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180) ~[hibernate-core-5.4.26.Final.jar:5.4.26.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68) ~[hibernate-core-5.4.26.Final.jar:5.4.26.Final]
```

How to reproduce: Launch the webapp locally.

### PR DESCRIPTION
**Pull request by tomaszsmy**
close #1191

### CODE REVIEW

**Review by nya-elimuai — APPROVED** [review]
This worked great 🙂

Thank you!

**Comment by nya-elimuai** [comment]
@tomaszsmy Ready to be merged 👍🏽

**Review by vrudas — COMMENTED** [review]
[optional recommendation] Method `CustomDispatcherServlet::getConnectionProvider` can be extracted into a dedicated class to reduce amount of code in a `CustomDispatcherServlet` class

File: src/main/java/ai/elimu/web/ConnectionProviderWeb.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+import java.sql.Connection;
+import java.sql.DriverManager;
+import java.sql.SQLException;
+
+public class ConnectionProviderWeb implements ConnectionProvider {
+
+    @Override
+    public Connection getConnection() throws SQLException {
+        return DriverManager.getConnection(ConfigHelper.getProperty("jdbc.url"), ConfigHelper.getProperty("jdbc.username"), ConfigHelper.getProperty("jdbc.password"));
```
Comment (vrudas) [inline src/main/java/ai/elimu/web/ConnectionProviderWeb.java:14]: - good practice to pass required connection properties as an constructor arguments, this approach allow us to not couple `ConnectionProviderWeb` with an a singleton class `ConfigHelper` and makes code easier to support in future as we will control input dependencies of a class by constructor instead of unexpected behaviour in case of changed logic of `ConfigHelper` methods

**Review by vrudas — CHANGES_REQUESTED** [review]

File: src/main/java/ai/elimu/web/ConnectionProviderWeb.java (hunk 1 above)
Comment (vrudas) [reply src/main/java/ai/elimu/web/ConnectionProviderWeb.java:14]: @nya-elimuai, yes

Comment (nya-elimuai) [reply src/main/java/ai/elimu/web/ConnectionProviderWeb.java:14]: ☝🏽 @tomaszsmy

File: src/main/java/ai/elimu/web/ConnectionProviderWeb.java [hunk 2]
```diff
@@ -0,0 +1,43 @@
+package ai.elimu.web;
+
+import ai.elimu.util.ConfigHelper;
```
Comment (nya-elimuai) [inline src/main/java/ai/elimu/web/ConnectionProviderWeb.java:3]: Remove unused import:
```suggestion
```

File: src/main/java/ai/elimu/web/ConnectionProviderWeb.java [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+import org.hibernate.engine.jdbc.connections.spi.ConnectionProvider;
+
+import java.sql.Connection;
+import java.sql.DriverManager;
+import java.sql.SQLException;
+
+public class ConnectionProviderWeb implements ConnectionProvider {
+    private final String url;
```
Comment (nya-elimuai) [inline src/main/java/ai/elimu/web/ConnectionProviderWeb.java:11]:
```suggestion
public class ConnectionProviderWeb implements ConnectionProvider {

    private final String url;
```

File: src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java [hunk 4]
```diff
@@ -60,11 +62,12 @@ protected WebApplicationContext initWebApplicationContext() {
      */
     private void createJpaSchemaExport() {
         logger.info("createJpaSchemaExport");
-        
+
         ServiceRegistry serviceRegistry = new StandardServiceRegistryBuilder()
 //                .configure("META-INF/jpa-persistence.xml")
                 .applySetting("hibernate.dialect", ConfigHelper.getProperty("jpa.databasePlatform"))
                 .applySetting("hibernate.hbm2ddl.auto", "update")
+                .applySetting(AvailableSettings.CONNECTION_PROVIDER, new ConnectionProviderWeb(ConfigHelper.getProperty("jdbc.url"), ConfigHelper.getProperty("jdbc.username"), ConfigHelper.getProperty("jdbc.password")))
```
Comment (nya-elimuai) [inline src/main/java/ai/elimu/web/servlet/CustomDispatcherServlet.java:70]: I suggest preparing a separate variable for improved readability:
```suggestion
        ConnectionProviderWeb connectionProviderWeb = new ConnectionProviderWeb(ConfigHelper.getProperty("jdbc.url"), ConfigHelper.getProperty("jdbc.username"), ConfigHelper.getProperty("jdbc.password"));
        ServiceRegistry serviceRegistry = new StandardServiceRegistryBuilder()
//                .configure("META-INF/jpa-persistence.xml")
                .applySetting("hibernate.dialect", ConfigHelper.getProperty("jpa.databasePlatform"))
                .applySetting("hibernate.hbm2ddl.auto", "update")
                .applySetting(AvailableSettings.CONNECTION_PROVIDER, connectionProviderWeb)
```

**Review by nya-elimuai — APPROVED** [review]

**Review by nya-elimuai — APPROVED** [review]

**Comment by nya-elimuai** [comment]
> [optional recommendation] Method `CustomDispatcherServlet::getConnectionProvider` can be extracted into a dedicated class to reduce amount of code in a `CustomDispatcherServlet` class

Thank you for making the suggestion, @vrudas. Could you review again, please? 🙂
