### PR TITLE
1823 null pointer exception when importing storyweaver e pub

### LINKED ISSUE #1823: NullPointerException when importing Storyweaver ePUB
Getting an error when importing this Tagalog ePUB (from Storyweaver): https://github.com/elimu-ai/webapp/blob/main/src/test/resources/ai/elimu/util/epub/tgl-sw-105391-tayo-ay-magbilang.epub

URL: http://localhost:8080/webapp/content/storybook/create-from-epub

```java
...

tgl-sw-105391-tayo-ay-magbilang.epub_unzipped\OEBPS\11.xhtml
tgl-sw-105391-tayo-ay-magbilang.epub_unzipped\OEBPS\12.xhtml
tgl-sw-105391-tayo-ay-magbilang.epub_unzipped\OEBPS\toc.ncx 
tgl-sw-105391-tayo-ay-magbilang.epub_unzipped\OEBPS\nav.html
tableOfContentsFile: "tgl-sw-105391-tayo-ay-magbilang.epub_unzipped\OEBPS\nav.html"
[WARNING] /webapp/content/storybook/create-from-epub
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "chapterReferences" is null
    at org.springframework.web.servlet.FrameworkServlet.processRequest (FrameworkServlet.java:1014)        
    at org.springframework.web.servlet.FrameworkServlet.doPost (FrameworkServlet.java:909)

...

    at java.lang.Thread.run (Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "chapterReferences" is null
    at ai.elimu.web.content.storybook.StoryBookCreateFromEPubController.handleSubmit (StoryBookCreateFromEPubController.java:225)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
```

### PR DESCRIPTION
**Pull request by vrudas**
Resolves #1823

Add an additional check for `.html` extension of the Table of Contents file

### Technical Details

Moved logic to a separate service to reduce code base and logic inside a Controller class

### Testing Instructions

Wrote Unit tests for a new service class

### Screenshots

Screenshot 2024-08-22 at 11 52 42

### CODE REVIEW

**Review by Souvik-Cyclic — APPROVED** [review]

File: src/test/java/ai/elimu/service/storybook/StoryBookEPubServiceTest.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+        "file_name",
+        "file-name",
+        "file.name"
+    })
+    void check_not_valid_table_of_contents_file_name(String fileName) {
+        assertFalse(storyBookEPubService.isTableOfContentsFileHtmlLike(fileName));
+    }
+
+    @ParameterizedTest(name = "fileName = {0}")
+    @ValueSource(strings = {"fileName.xhtml", "fileName.html"})
```
Comment (jo-elimu) [inline src/test/java/ai/elimu/service/storybook/StoryBookEPubServiceTest.java:40]: Maybe add another unit test for the `toc.ncx` filename as well?

**Review by jo-elimu — APPROVED** [review]
